export const hoverColorVariants: Record<string, string> = {
  blueDeep: "hover:bg-blue-deep",
  boldGray: "hover:bg-bold-gray",
  lightGray: "hover:bg-light-gray",
  mediumGray: "hover:bg-medium-gray",
  mediumBrown: "hover:bg-medium-brown",
  blueSmoky: "hover:bg-blue-smoky",
  blueSky: "hover:bg-blue-sky",
  blueClear: "hover:bg-blue-clear",
  blueVeryLight: "hover:bg-blue-very-light",
  orangeHtml: "hover:bg-orange-html",
  blueCss: "hover:bg-blue-css",
  yellowJs: "hover:bg-yellow-js",
  blueTs: "hover:bg-blue-ts",
  blueReact: "hover:bg-blue-react",
  purpleVite: "hover:bg-purple-vite",
  blueTailwind: "hover:bg-blue-tailwind",
  blueMui: "hover:bg-blue-mui",
  purpleAxios: "hover:bg-purple-axios",
  blueMysql: "hover:bg-blue-mysql",
  brownMariaDb: "hover:bg-brown-mariadb",
  orangeGit: "hover:bg-orange-git",
  blueDocker: "hover:bg-blue-docker",
  black: "hover:bg-black",
};
